### ISSUE TITLE
maybe something wrong

### ISSUE THREAD

**Issue by alexwhen** [AntonioMeireles/kubernetes-vagrant-coreos-cluster#1]
core@master ~ $ systemctl status setup-network
● setup-network.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
core@master ~ $ systemctl status setup-network-environment -l
● setup-network-environment.service - Setup Network Environment
   Loaded: loaded (/etc/systemd/system/setup-network-environment.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2015-05-25 17:49:37 ; 54s ago
     Docs: https://github.com/kelseyhightower/setup-network-environment
  Process: 956 ExecStartPre=/usr/bin/curl -Ls -o /opt/bin/setup-network-environment -z /opt/bin/setup-network-environment https://github.com/kelseyhightower/setup-network-environment/releases/download/v1.0.0/setup-network-environment (code=exited, status=7)
  Process: 953 ExecStartPre=/usr/bin/mkdir -p /opt/bin (code=exited, status=0/SUCCESS)

May 25 17:49:35 master systemd[1]: Starting Setup Network Environment...
May 25 17:49:37 master systemd[1]: setup-network-environment.service: control process exited, code=exited status=7
May 25 17:49:37 master systemd[1]: Failed to start Setup Network Environment.
May 25 17:49:37 master systemd[1]: Unit setup-network-environment.service entered failed state.
May 25 17:49:37 master systemd[1]: setup-network-environment.service failed.

**Comment by AntonioMeireles** [comment]
hi, can yoy please provider more data, for context ? hypervisor in use, host OS, etc. 

thanks in advance

**Comment by alexwhen** [comment]
virtualbox and osx10.10.4

**Comment by AntonioMeireles** [comment]
humm. this _may_ be a transient issue derivated from some weird github beahviour. can you try again please ? (vagrant destroy -f; vagrant up)

**Comment by alexwhen** [comment]
core@master ~ $ journalctl -xe
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master docker[1351]: Error response from daemon: no such id
May 25 18:09:16 master docker[1351]: time="2015-05-25T18:09:16Z" level=fata
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: No such image: quay.io/coreos/flannel:
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master sdnotify-proxy[1366]: Unable to find image 'quay.io/
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: invalid registry endpoint https://quay
May 25 18:09:16 master dockerd[971]: v2 ping attempt failed with error: Get
May 25 18:09:16 master dockerd[971]: v1 ping attempt failed with error: Get
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master docker[1372]: time="2015-05-25T18:09:16Z" level=fata
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: invalid registry endpoint https://quay
May 25 18:09:16 master dockerd[971]: v2 ping attempt failed with error: Get
May 25 18:09:16 master dockerd[971]: v1 ping attempt failed with error: Get
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=info
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master systemd[1]: docker-cache.service: control process ex
May 25 18:09:16 master systemd[1]: Failed to start Docker cache proxy.
-- Subject: Unit docker-cache.service has failed
-- Defined-By: systemd

## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

## -- Unit docker-cache.service has failed.

-- The result is failed.
May 25 18:09:16 master systemd[1]: Dependency failed for Docker Application
-- Subject: Unit docker.service has failed
-- Defined-By: systemd

## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

## -- Unit docker.service has failed.

-- The result is dependency.
May 25 18:09:16 master systemd[1]: Job docker.service/start failed with res
May 25 18:09:16 master systemd[1]: Unit docker-cache.service entered failed
May 25 18:09:16 master systemd[1]: docker-cache.service failed.
May 25 18:09:16 master dockerd[971]: time="2015-05-25T18:09:16Z" level=erro
May 25 18:09:16 master sdnotify-proxy[1366]: time="2015-05-25T18:09:16Z" le
May 25 18:09:16 master systemd[1]: flanneld.service: main process exited, c
May 25 18:09:16 master systemd[1]: Failed to start Network fabric for conta
-- Subject: Unit flanneld.service has failed
-- Defined-By: systemd

## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

## -- Unit flanneld.service has failed.

-- The result is failed.
May 25 18:09:16 master systemd[1]: Unit flanneld.service entered failed sta
May 25 18:09:16 master systemd[1]: flanneld.service failed.
lines 2990-3054/3054 (END)

**Comment by AntonioMeireles** [comment]
is that in second boot ? i mean - so in your case this is reproducible ?

**Comment by alexwhen** [comment]
yes ,maybe the reason is GFW in china,i will try proxy

**Comment by AntonioMeireles** [comment]
ah, ok. do plz. afaict it should just work ... (will be afk in next few hours). will look at your finding early tomorrow.

**Comment by AntonioMeireles** [comment]
@alexwhen i strongly suspect that you were right. Github hosted content is being blocked in-transit before you can consume it by PRC's GFW... using a proxy should fix it afaict. :-)

**Comment by alexwhen** [comment]
==> node-01: Importing base box 'coreos-alpha'...
==> node-01: Matching MAC address for NAT networking...
==> node-01: Checking if box 'coreos-alpha' is up to date...
==> node-01: Setting the name of the VM: kvc_node-01_1432704358802_78637
==> node-01: Fixed port collision for 22 => 2222. Now on port 2200.
==> node-01: Clearing any previously set network interfaces...
==> node-01: Preparing network interfaces based on configuration...
    node-01: Adapter 1: nat
    node-01: Adapter 2: hostonly
==> node-01: Forwarding ports...
    node-01: 22 => 2200 (adapter 1)
==> node-01: Running 'pre-boot' VM customizations...
==> node-01: Booting VM...
==> node-01: Waiting for machine to boot. This may take a few minutes...
    node-01: SSH address: 127.0.0.1:2200
    node-01: SSH username: core
    node-01: SSH auth method: private key
    node-01: Warning: Connection timeout. Retrying...
==> node-01: Machine booted and ready!
==> node-01: Setting hostname...
==> node-01: Configuring and enabling network interfaces...
==> node-01: Running provisioner: file...
==> node-01: Running provisioner: shell...
    node-01: Running: inline script
==> node-01: Running triggers after up...
==> node-01: waiting for node-01 (172.17.8.102) to be ready...
WARNING: something going wrong - http://172.17.8.102:10250 (node-01 (172.17.8.102)) taking too long to respond.
==> node-02: Importing base box 'coreos-alpha'...
==> node-02: Matching MAC address for NAT networking...
==> node-02: Checking if box 'coreos-alpha' is up to date...
==> node-02: Setting the name of the VM: kvc_node-02_1432704882435_41550
==> node-02: Fixed port collision for 22 => 2222. Now on port 2201.
==> node-02: Clearing any previously set network interfaces...
==> node-02: Preparing network interfaces based on configuration...
    node-02: Adapter 1: nat
    node-02: Adapter 2: hostonly
==> node-02: Forwarding ports...
    node-02: 22 => 2201 (adapter 1)
==> node-02: Running 'pre-boot' VM customizations...
==> node-02: Booting VM...
==> node-02: Waiting for machine to boot. This may take a few minutes...
    node-02: SSH address: 127.0.0.1:2201
    node-02: SSH username: core
    node-02: SSH auth method: private key
    node-02: Warning: Connection timeout. Retrying...
==> node-02: Machine booted and ready!
==> node-02: Setting hostname...
==> node-02: Configuring and enabling network interfaces...
==> node-02: Running provisioner: file...
==> node-02: Running provisioner: shell...
    node-02: Running: inline script
==> node-02: Running triggers after up...
==> node-02: waiting for node-02 (172.17.8.103) to be ready...
WARNING: something going wrong - http://172.17.8.103:10250 (node-02 (172.17.8.103)) taking too long to respond.

**Comment by alexwhen** [comment]
Volumes/project/kvc $ flm
The authenticity of host '[127.0.0.1]:2200' can't be established.
RSA key fingerprint is 29:83:ff:99:d5:f7:ec:6c:5b:1e:96:23:f8:40:f5:64.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:2200' (RSA) to the list of known hosts.
MACHINE     IP      METADATA
001c2cf6... 172.17.8.101    role=master
45e8a433... 172.17.8.103    role=minion
9e5911f6... 172.17.8.102    role=minion
:+1:  

Thank you very much!

**Comment by alexwhen** [comment]
:+1:  :100:
